"""empty message

Revision ID: 4445b27825ca
Revises: c4196cef4b6f
Create Date: 2021-07-11 17:55:37.564546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4445b27825ca'
down_revision = 'c4196cef4b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('references', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'references', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'references', type_='foreignkey')
    op.drop_column('references', 'user_id')
    op.drop_column('references', 'created_at')
    # ### end Alembic commands ###
