"""empty message

Revision ID: 4c7bf7352643
Revises: 4c340ec8202e
Create Date: 2021-07-06 19:08:43.890901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7bf7352643'
down_revision = '4c340ec8202e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('applicationId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'applications', ['applicationId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'applicationId')
    # ### end Alembic commands ###
