"""empty message

Revision ID: bc66e137a6bd
Revises: 
Create Date: 2021-06-30 16:31:00.403117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc66e137a6bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screen_shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('apply_weekly_goal', sa.Integer(), nullable=True),
    sa.Column('base_resume', sa.String(), nullable=True),
    sa.Column('base_cv', sa.String(), nullable=True),
    sa.Column('base_cover_letter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('url_link', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('resume', sa.String(), nullable=True),
    sa.Column('cv', sa.String(), nullable=True),
    sa.Column('cover_letter', sa.String(), nullable=True),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['applicant'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_references',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reference_id')
    )
    op.create_table('application_notes',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'note_id')
    )
    op.create_table('application_screen_shots',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('screen_shot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['screen_shot_id'], ['screen_shots.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'screen_shot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_screen_shots')
    op.drop_table('application_notes')
    op.drop_table('user_references')
    op.drop_table('applications')
    op.drop_table('users')
    op.drop_table('screen_shots')
    op.drop_table('references')
    op.drop_table('notes')
    # ### end Alembic commands ###
